"""
DuckDB Forecast Analysis Utilities for Quartz Solar Forecast

Utility functions to efficiently query and analyze forecast data generated by
forecast_csv.py and multi_site_generate_forecasts.py using DuckDB.
"""

import duckdb
import pandas as pd
from pathlib import Path
from typing import Optional, List, Dict, Union
from datetime import datetime


class ForecastAnalyzer:
    """
    Efficient forecast data analysis using DuckDB.
    
    Designed to work with outputs from forecast_csv.py and
    multi_site_generate_forecasts.py without loading all data into memory.
    """
    
    def __init__(self, data_dir: Union[str, Path], db_path: Optional[str] = None):
        """
        Initialize the analyzer.
        
        Args:
            data_dir: Directory containing forecast CSV/Parquet files
            db_path: Optional persistent database path. If None, uses in-memory DB
        """
        self.data_dir = Path(data_dir)
        self.db_path = db_path or ":memory:"
        self.con = duckdb.connect(self.db_path)
        self._setup_views()
        
    def _setup_views(self):
        """Create unified view of forecast data with normalized columns."""
        csv_files = list(self.data_dir.glob("*.csv"))
        if not csv_files:
            return

        # Use DuckDB to probe the first CSV so we get the same column names
        first_file = str(csv_files[0]).replace("\\", "/")
        try:
            sample_df = self.con.execute(
                f"SELECT * FROM read_csv_auto('{first_file}', header=true, normalize_names=true, sample_size=1) LIMIT 1"
            ).fetchdf()
        except Exception as e:
            print(f"Warning: Could not read sample file with DuckDB: {e}")
            return

        orig_cols = sample_df.columns.tolist()
        # Find timestamp column (common normalized names)
        timestamp_candidates = [c for c in orig_cols if c.lower() == 'timestamp' or c.lower().startswith('unnamed') or c.lower().startswith('column0')]
        timestamp_col = timestamp_candidates[0] if timestamp_candidates else orig_cols[0]

        # Identify power columns (normalized)
        power_cols = [col for col in orig_cols if 'power' in col.lower()]

        if not power_cols:
            print("Warning: no power-like columns found in sample file; view not created")
            return

        # Build SQL using normalized names and aliasing the CSV reader as raw
        power_sum = ' + '.join([f'"{col}"' for col in power_cols])
        other_cols = ', '.join([f'"{col}"' for col in power_cols])
        data_dir_str = str(self.data_dir).replace("\\", "/")

        view_sql = f"""
        CREATE OR REPLACE VIEW forecasts AS
        SELECT
            CAST("{timestamp_col}" AS TIMESTAMP) AS timestamp,
            {power_sum} AS total_power_kw,
            {other_cols}
        FROM read_csv_auto('{data_dir_str}/*.csv', header=true, normalize_names=true) AS raw
        """

        try:
            self.con.execute(view_sql)
        except Exception as e:
            print(f"Warning: Could not create unified view: {e}")
        
    def __enter__(self):
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
        
    def close(self):
        """Close the database connection."""
        if self.con:
            self.con.close()
    
    def get_schema(self) -> pd.DataFrame:
        """
        Get the schema of the forecast data.
        
        Returns:
            DataFrame with column names and types
        """
        try:
            return self.con.execute("DESCRIBE forecasts").fetchdf()
        except:
            return pd.DataFrame({'error': ['No data loaded or view not created']})
    
    def daily_summary(self, start_date=None, end_date=None, site_pattern=None):
        """
        Daily summary of forecast data.
        
        Args:
            start_date: Optional start date for filtering (inclusive)
            end_date: Optional end date for filtering (exclusive)
            site_pattern: Optional site name pattern for filtering
            
        Returns:
            DataFrame with daily summary statistics
        """
        # Use PRAGMA table_info and be robust to the returned column name for the column list.
        pragma_df = self.con.execute("PRAGMA table_info('forecasts')").fetchdf()
        # detect which column holds the column name (duckdb may expose it as 'name' or 'column_name', etc.)
        if 'column_name' in pragma_df.columns:
            name_col = 'column_name'
        elif 'name' in pragma_df.columns:
            name_col = 'name'
        else:
            # fallback to first textual column that isn't type/nullable/default/pk
            candidates = [c for c in pragma_df.columns if pragma_df[c].dtype == object]
            if not candidates:
                raise RuntimeError("Unable to determine column name field from PRAGMA table_info output")
            name_col = candidates[0]

        all_columns = [str(x) for x in pragma_df[name_col].tolist()]

        # find power-like columns
        power_cols = [c for c in all_columns if 'power' in c.lower()]
        if not power_cols:
            power_cols = [c for c in all_columns if any(k in c.lower() for k in ('kw', 'gen', 'energy'))]

        if not power_cols:
            raise ValueError("No power-like columns found in 'forecasts' table")

        total_power_expr = " + ".join([f"COALESCE(\"{c}\", 0)" for c in power_cols])

        where_clauses = []
        if start_date:
            where_clauses.append(f"timestamp >= '{start_date}'")
        if end_date:
            where_clauses.append(f"timestamp < '{end_date}'")
        if site_pattern:
            where_clauses.append(f"site_name LIKE '{site_pattern}'")

        where_sql = "WHERE " + " AND ".join(where_clauses) if where_clauses else ""

        sql = f"""
            SELECT
                date_trunc('day', timestamp) AS date,
                COUNT(*) AS count_rows,
                AVG({total_power_expr}) AS avg_power_kw,
                MAX({total_power_expr}) AS peak_power_kw,
                SUM({total_power_expr}) AS total_energy_kwh
            FROM forecasts
            {where_sql}
            GROUP BY date
            ORDER BY date
        """

        return self.con.execute(sql).fetchdf()
    
    def site_comparison(self, metric: str = 'avg_power_kw') -> pd.DataFrame:
        """
        Compare performance metrics across different sites.
        
        Args:
            metric: Metric to compare ('avg_power_kw', 'peak_power_kw', 'total_energy')
            
        Returns:
            DataFrame with site comparison
        """
        csv_files = list(self.data_dir.glob("*.csv"))
        if not csv_files:
            return pd.DataFrame()
        
        results = []
        for csv_file in csv_files:
            df = pd.read_csv(csv_file, index_col=0)
            df.index = pd.to_datetime(df.index)
            
            # Extract all Site columns
            power_cols = [col for col in df.columns if 'Power' in col or 'power' in col]
            site_names = set()
            for col in df.columns:
                parts = col.split('_')
                if parts[0].startswith('Site') or parts[0].startswith('site'):
                    site_names.add(parts[0])
            
            for site in sorted(site_names):
                # Try both capitalization patterns
                power_col = f"{site} Power"
                if power_col not in df.columns:
                    power_col = f"{site.lower()} power"
                    
                if power_col in df.columns:
                    power_data = df[power_col]
                    results.append({
                        'site_name': site,
                        'total_forecasts': len(power_data),
                        'avg_power_kw': power_data.mean(),
                        'peak_power_kw': power_data.max(),
                        'total_energy_kwh': power_data.sum(),
                        'first_forecast': df.index.min(),
                        'last_forecast': df.index.max()
                    })
        
        result_df = pd.DataFrame(results)
        if len(result_df) > 0:
            result_df = result_df.sort_values(by=metric, ascending=False)
        
        return result_df
    
    def hourly_profile(
        self,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None
    ) -> pd.DataFrame:
        """
        Generate typical hourly generation profile.
        
        Returns:
            DataFrame with hourly averages
        """
        csv_files = list(self.data_dir.glob("*.csv"))
        if not csv_files:
            return pd.DataFrame()
        
        dfs = []
        for csv_file in csv_files:
            df = pd.read_csv(csv_file, index_col=0)
            df.index = pd.to_datetime(df.index)
            power_cols = [col for col in df.columns if 'Power' in col or 'power' in col]
            if power_cols:
                df['total_power_kw'] = df[power_cols].sum(axis=1)
                dfs.append(df[['total_power_kw']])
        
        if not dfs:
            return pd.DataFrame()
        
        combined_df = pd.concat(dfs, axis=1)
        combined_df['power_kw'] = combined_df.filter(like='total_power_kw').sum(axis=1)
        
        # Filter by dates if provided
        if start_date:
            combined_df = combined_df[combined_df.index >= start_date]
        if end_date:
            combined_df = combined_df[combined_df.index <= end_date]
        
        # Extract hour and calculate statistics
        combined_df['hour'] = combined_df.index.hour
        hourly = combined_df.groupby('hour')['power_kw'].agg([
            ('sample_count', 'count'),
            ('avg_power_kw', 'mean'),
            ('p25', lambda x: x.quantile(0.25)),
            ('p50', lambda x: x.quantile(0.50)),
            ('p75', lambda x: x.quantile(0.75)),
            ('max_power_kw', 'max')
        ]).reset_index()
        hourly.rename(columns={'hour': 'hour_of_day'}, inplace=True)
        
        return hourly
    
    def peak_periods(self, limit: int = 20) -> pd.DataFrame:
        """
        Get the top peak generation periods.
        
        Args:
            limit: Number of top periods to return
            
        Returns:
            DataFrame with peak periods
        """
        try:
            sql = f"""
            SELECT timestamp, total_power_kw
            FROM forecasts
            WHERE total_power_kw > 0
            ORDER BY total_power_kw DESC
            LIMIT {limit}
            """
            return self.con.execute(sql).fetchdf()
        except Exception as e:
            print(f"Error getting peak periods: {e}")
            # Fallback to pandas
            csv_files = list(self.data_dir.glob("*.csv"))
            if not csv_files:
                return pd.DataFrame()
            
            dfs = []
            for csv_file in csv_files:
                df = pd.read_csv(csv_file, index_col=0)
                df.index = pd.to_datetime(df.index)
                power_cols = [col for col in df.columns if 'Power' in col or 'power' in col]
                if power_cols:
                    df['total_power_kw'] = df[power_cols].sum(axis=1)
                    dfs.append(df[['total_power_kw']])
            
            if dfs:
                combined_df = pd.concat(dfs)
                combined_df = combined_df[combined_df['total_power_kw'] > 0]
                return combined_df.nlargest(limit, 'total_power_kw').reset_index()
            
            return pd.DataFrame()
    
    def export_filtered(
        self,
        output_file: str,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        min_power: Optional[float] = None,
        output_format: str = 'parquet'
    ) -> None:
        """
        Export filtered forecast data without loading into memory.
        
        Args:
            output_file: Output file path
            start_date: Filter start date
            end_date: Filter end date
            min_power: Minimum power threshold
            output_format: 'parquet' or 'csv'
        """
        csv_files = list(self.data_dir.glob("*.csv"))
        if not csv_files:
            print("No CSV files found in directory")
            return
        
        dfs = []
        for csv_file in csv_files:
            df = pd.read_csv(csv_file, index_col=0)
            df.index = pd.to_datetime(df.index)
            
            # Filter by dates if provided
            if start_date:
                df = df[df.index >= start_date]
            if end_date:
                df = df[df.index <= end_date]
            
            # Filter by minimum power if provided
            if min_power is not None:
                power_cols = [col for col in df.columns if 'Power' in col or 'power' in col]
                if power_cols:
                    df = df[(df[power_cols] >= min_power).any(axis=1)]
            
            dfs.append(df)
        
        if not dfs:
            print("No data after filtering")
            return
        
        combined_df = pd.concat(dfs)
        combined_df = combined_df.sort_index()
        
        # Export to file
        if output_format.lower() == 'parquet':
            combined_df.to_parquet(output_file)
        else:
            combined_df.to_csv(output_file)
        
        print(f"Exported filtered data to {output_file}")
    
    def query(self, sql: str) -> pd.DataFrame:
        """
        Execute custom SQL query on forecast data using DuckDB.
        
        The data is accessible via the 'forecasts' view with columns:
        - timestamp: Forecast timestamp
        - total_power_kw: Sum of all site power values
        - Individual site power columns (site1_power, site2_power, etc.)
        
        Args:
            sql: Custom SQL query
            
        Returns:
            Query results as DataFrame
            
        Example:
            >>> sql = "SELECT * FROM forecasts WHERE total_power_kw > 100 LIMIT 10"
            >>> results = analyzer.query(sql)
        """
        try:
            return self.con.execute(sql).fetchdf()
        except Exception as e:
            print(f"Query error: {e}")
            print("\nAvailable schema:")
            print(self.get_schema())
            return pd.DataFrame()


def quick_analysis(data_dir: str, output_summary: bool = True) -> Dict:
    """
    Convenience function for quick forecast analysis.
    
    Args:
        data_dir: Directory containing forecast files
        output_summary: Print summary to console
        
    Returns:
        Dictionary with analysis results
    """
    with ForecastAnalyzer(data_dir) as analyzer:
        results = {
            'daily_summary': analyzer.daily_summary(),
            'hourly_profile': analyzer.hourly_profile(),
            'site_comparison': analyzer.site_comparison(),
            'peak_periods': analyzer.peak_periods(limit=10)
        }
        
        if output_summary:
            print("=" * 60)
            print("FORECAST ANALYSIS SUMMARY")
            print("=" * 60)
            
            print("\nDaily Summary (Last 5 days):")
            if not results['daily_summary'].empty:
                print(results['daily_summary'].tail())
            else:
                print("No daily summary data available.")
            
            print("\nHourly Profile (Daylight Hours):")
            hp = results['hourly_profile']
            if hp.empty or 'avg_power_kw' not in hp.columns:
                print("No hourly data available.")
            else:
                daylight = hp[hp['avg_power_kw'] > 0]
                print(daylight)
            
            print("\nSite Comparison:")
            if not results['site_comparison'].empty:
                print(results['site_comparison'])
            else:
                print("No site comparison data available.")
            
            print("\nTop 10 Peak Periods:")
            if not results['peak_periods'].empty:
                print(results['peak_periods'])
            else:
                print("No peak period data available.")
            
        return results


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Analyze Quartz Solar Forecast data with DuckDB"
    )
    parser.add_argument(
        'data_dir',
        help="Directory containing forecast CSV files"
    )
    parser.add_argument(
        '--start-date',
        help="Start date for analysis (YYYY-MM-DD)"
    )
    parser.add_argument(
        '--end-date',
        help="End date for analysis (YYYY-MM-DD)"
    )
    parser.add_argument(
        '--export',
        help="Export filtered data to file"
    )
    parser.add_argument(
        '--format',
        choices=['csv', 'parquet'],
        default='parquet',
        help="Export format (default: parquet)"
    )
    parser.add_argument(
        '--min-power',
        type=float,
        help="Minimum power threshold for filtering"
    )
    
    args = parser.parse_args()
    
    # Run quick analysis
    results = quick_analysis(args.data_dir)
    
    # Export if requested
    if args.export:
        with ForecastAnalyzer(args.data_dir) as analyzer:
            analyzer.export_filtered(
                output_file=args.export,
                start_date=args.start_date,
                end_date=args.end_date,
                min_power=args.min_power,
                output_format=args.format
            )