name: API Tests + Docker build (branch)
run-name: 'Test branch commit "${{ github.event.head_commit.message }}"'

on:  
  push:
    branches-ignore: [ "main" ]
    paths-ignore: ['README.md']

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install ruff
        run: pip install ruff
      
      - name: Run ruff linting
        run: ruff check .
      
      - name: Run ruff formatting check
        run: ruff format --check .

  tests:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@main
    secrets: inherit
    with:
      enable_linting: false
      enable_typechecking: false
      containerfile: Dockerfile
      tests_folder: 'tests/unit/api_tests'
      tests_matrix: true
      test_python_versions: '["3.11"]'