name: API Tests + Docker build (branch)
run-name: 'Test branch commit "${{ github.event.head_commit.message }}"'

on:  
  push:
    branches-ignore: [ "main" ]

    paths-ignore: ['README.md']

jobs:
  branch-ci:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@main
    secrets: inherit
    with:
      enable_linting: true
      enable_typechecking: false
      containerfile: Dockerfile
      tests_folder: 'tests/unit/api_tests'
      tests_matrix: true
      test_python_versions: '["3.11"]'