name: Run forecast

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: upload forecast to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_PUSH }}
          HF_REPO: ${{ secrets.HF_REPO }}
        run: |
          python scripts/hf_upload.py

